spring.application.name=The-tuna-is-4jo-team-project

# portOne
portone.base-url=https://api.portone.io
portone.api-secret=${PORTONE_API_SECRET}
portone.store-id=${PORTONE_STORE_ID}
portone.channel-key=${PORTONE_CHANNEL_KEY}
portone.webhook-secret=${PORTONE_WEBHOOK_SECRET}