spring:
  config:
    activate:
      on-profile: prod
    import: optional:aws-parameterstore:/tuna/prod/

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true

jwt:
  secret: ${JWT_SECRET}

portone:
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}
